apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ek509e2x2-go
  janus-idp.io/tekton: ek509e2x2-go
  backstage.io/kubernetes-id: ek509e2x2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ek509e2x2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
