apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ek509e2x2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ek509e2x2-go 
  name: ek509e2x2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ek509e2x2-go 
